# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62fea2005925fc58727a64ccc45266d198875074ef2f4a5597900da9b7109601dde2cd635f15b032cf382a7555a6ed32e3b853cb74d73135fa5a6583ebb23b6e

test:
  secret_key_base: 3101bd4feb77624e69363bd4a5f8ae7f4b2087192d8754f5feeac2f011ca9af8ba0327b811e479de59b0b269fa8ee159d8a3f9363531e406c7522c06949ff2f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
